### ISSUE TITLE
Find ball speed and direction

### ISSUE THREAD

**Issue by gortium** [Naova/NaovaCodeRelease#18]

**Comment by bbrulard** [comment]
Currently handled in Goaler.h with the following lines:

`libCodeRelease.between(theBallModel.estimate.position.x(),0.f,1000.f)`
-»Retourne la presence de la balle selon l'axe x entre 0 et 1000mm de la ref 0 (robot)
Fonctionne aussi pour l'axe y evidemment.

De même, on a
`libCodeRelease.between(theBallModel.estimate.velocity.x(),1.f,1000.f)`
-»Retourne si la vitesse estimée de la balle est entre 1 et 1000mm/sec

**Comment by gortium** [comment]
Good, je close celle-ci et #17 étant donné qu'on a position, vélocité et que la vélocité gère l'orientation.
