### ISSUE TITLE
Keeper state machine 

### ISSUE THREAD

**Issue by gortium** [Naova/NaovaCodeRelease#19]
Let discuss and find our goalie strategies here

**Comment by gortium** [comment]
keeper go to the ball if he is closer than opponents. And kick it.

**Comment by gortium** [comment]
Move to the position between the ball and the goal

**Comment by bbrulard** [comment]
// Le keeper se retrouve dans des situations où il est dos à l'action

If Keeper can't see ball,{
     scan field with head

     If still can't see ball, {
            check position on the field and direction facing.

            If not facing field,{
                  turn around
            }
    }
}
