### ISSUE TITLE
Seance de recrutement

### ISSUE THREAD

**Issue by vgirardeau** [Naova/NaovaCodeRelease#205]
## Liste de chose à faire : 
- [ ] Trouver une date
- [ ] Trouver une salle
- [ ] Faire un event FB
- [ ] Faire une image de couverture pour l'event
- [ ] Faire une affiche pour les zone d'affichage de l'école
- [ ] Faire une annonce infolettre ecole
- [ ] Faire annonce sur page Fb des LOG - TI et ELE
- [ ] Powerpoint
- [ ] Vraiment le faire !

**Comment by gortium** [comment]
A voir si on en a besoin avec les 6 nouveaux et le 5 a 7 élé à venir.
