### ISSUE TITLE
How execute the Goalie code in simulation?

### ISSUE THREAD

**Issue by wmarc04** [Naova/NaovaCodeRelease#22]

**Comment by gortium** [comment]
Dans le PDF de Bhuman j'ai trouvé ça ! On peux donc choisir le numero de joueur et son équipe par son argument "name­"­
> <Compound name=“robots”>: This compound contains all active robots, i. e. robots for
> which processes will be created. So, all robots in this compound will move on their own.
> However, each of them will require a lot of computation time. In the tag Body, the attribute
> ref specifies which NAO model should be used and name sets the robot name in the scene
> graph of the simulation. Legal robot names are “robot1” . . . “robot10”, where the first five
> robots are assumed to play in the blue team (with player numbers 1. . . 5) while the other
> five play in the red team (again with player numbers 1. . . 5). The standard color of the
> NAO’s jersey is set to blue. To set it to red, use <Set name=“NaoColor” value=“red”>
> within the tag Body.

**Comment by bbrulard** [comment]
On roule actuellement un Goalie en Simulation.
Le Handle écrit par Poup gere le choix des roles de joueurs en fonction de leur numero. Un robot numéro 1 sera toujours Goaler.

Pour un fichier de simu avec Goaler, partir de KeeperVsStricker.ros2, ou KeeperTrainingV2.ros2 dans Config/Scenes
