### ISSUE TITLE
What is Keeper in code?

### ISSUE THREAD

**Issue by wmarc04** [Naova/NaovaCodeRelease#24]

**Comment by wmarc04** [comment]
Il y a déjà du code qui gère le gardien. Dans le code c’est Kepper et non Goal ou  Goalie. Dans le fichier Settings.h, il y a tout les attributs qu’un robot peut avoir (teamNumber, teamColor, playerNumber,…) dont isGoalkeeper. Donc, si je comprend bien on crée les fichiers d’un robot et d’ajouter ce champs « isGoalkeeper=true » dans le fichier settings.cfg et voir ce qui se passe…

**Comment by wmarc04** [comment]
De plus, j'ai vu dans le code que lorsque le joueur a le numberPlayer a 1, il est gardien...

**Comment by bbrulard** [comment]
La liste des rôles prévus par B-Human est :

**Comment by gortium** [comment]
On close l'issue si réglé et on fera de la doc des closed issue après la qualif.
