### ISSUE TITLE
Set cameras permanent calibration for Naova's clubroom 

### ISSUE THREAD

**Issue by bbrulard** [Naova/NaovaCodeRelease#27]
On perd trop de temps à calibrer les caméras à chaque essaie. 
Il faut rentrer les valeurs ajustées comme settings par defaut  dans les fichiers passés aux robots.

Sans doutes dans un fichier .cfg type CameraConfig&co.

Une partie des bonnes valeures récupérées avec un _get representation_

`set representation:CameraSettings upper = { autoExposure = { value = 0; }; autoExposureAlgorithm = averageY; autoWhiteBalance = { value = 0; }; brightness = { value = -1000; }; contrast = { value = 64; }; exposure = { value = 120; }; fadeToBlack = { value = 0; }; gain = { value = 160; }; hue = { value = 0; }; saturation = { value = 160; }; sharpness = { value = 2; }; whiteBalance = { value = 3150; }; }; lower = { autoExposure = { value = 0; }; autoExposureAlgorithm = averageY; autoWhiteBalance = { value = 0; }; brightness = { value = -1000; }; contrast = { value = 64; }; exposure = { value = 120; }; fadeToBlack = { value = 0; }; gain = { value = 160; }; hue = { value = 0; }; saturation = { value = 160; }; sharpness = { value = 2; }; whiteBalance = { value = 3400; }; };`

**Comment by gortium** [comment]
L'ordre de recherche des config:

> 1. Config/Robots/<head name>/Head/<filename>
> • Used for files that only depend on the robot’s head
> • e.g.: Robots/Amy/Head/cameraIntrinsics.cfg
> 2. Config/Robots/<body name>/Body/<filename>
> • Used for files that only depend on the robot’s body
> • e.g.: Robots/Alex/Body/walkingEngine.cfg
> 3. Config/Robots/<head name>/<body name>/<filename>
> • Used for files that depend on both, the robot’s head and body.
> • e.g.: Robots/Amy/Alex/cameraCalibration.cfg
> 4. Config/Robots/<head name>/<filename>
> • If the head and body constellations for your robots are always the same, all files which
> belong to a robot may also be saved here.
> 5. Config/Robots/Default/<filename>
> 6. Config/Locations/<current location>/<filename>
> 7. Config/Locations/Default/<filename>
> 8. Config/<filename>
J'ai essayé de placer les fichier de config dans Config/Robots/Eve/ sans succès..
