### ISSUE TITLE
Start the game with whistle

### ISSUE THREAD

**Issue by jonathanf14** [Naova/NaovaCodeRelease#31]
En somme, il faut être en mesure de starter une game sur le coter du terrain et qu'avec le sifflet le robot prenne sa position.

**Comment by wmarc04** [comment]
Sais-tu si c'est possible de simuler un sifflet dans SimRobot?

**Comment by gortium** [comment]
Je crois avoir vue que le son pouvais etre simuler. mais aucune idée comment xD Sinon, se sera une condition dans la state machine du genre: si en simulation, ne pas attendre le sifflet.

**Comment by bbrulard** [comment]
En simu, c'est pas les 
gc initial
gc playing ?

Ca simule les messages du game controller, c'est pas mal la même affaire non?

**Comment by wmarc04** [comment]
Ouais, je pense qu'on veut que le state change avec le sifflet.

J'ai trouver ceci dans WhistleHandler =
`void WhistleHandler::update(GameInfo& gameInfo)
{
...
  if(overrideGameState)
  {
    if(checkForIllegalMotionPenalty())
    {
      timeOfLastSetState = theFrameInfo.time;
      overrideGameState = false;
    }
    else
    {
      gameInfo.state = STATE_PLAYING;
    }
  }
}`

**Comment by jonathanf14** [comment]
J'ai compris comment ca marche et maintenant le robot à un state Waitfornewsound, pour l'utiliser, il faut que je start une game avec le gamecontroleur et non en apputant sur le bouton du nao

**Comment by jonathanf14** [comment]
Tout le code est dans multiWhistleRecognizer.cpp
