### ISSUE TITLE
Placer les joueurs au début de partie

### ISSUE THREAD

**Issue by wmarc04** [Naova/NaovaCodeRelease#32]
En simulation, avec la scène Game2016.ros2, quand on passe par les game state (initial, ready, set, playing, ...). C'est au state «set» que les joueurs, qui sont au départ sur les lignes de touche, se placent sur le terrain.

**Comment by wmarc04** [comment]
Dans "Src/Controller/GameController.cpp", ça place automatiquement les robots en fonction de leurs rôle!

**Comment by gortium** [comment]
Hmm finalement je suis pas sur que GameController.cpp le fait. Je pense qu'il va falloir l'implementer nous même dans **/src/BehaviorControl/BehaviorControl2015/Options/GameControl/ReadyState.h**
