### ISSUE TITLE
Convertisseur .xar à .mof 

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#35]
Fichier sh. qui permet de convertir le .xar à un .txt qui comprend toutes les valeurs pour le fichier .MOF. 

-Amélioration futur avoir 1 ou 2 décimales max pour le "value final".

**Comment by arie1302** [comment]
Version 1 du convertisseur est fini. Amélioration n'est pas encore regardé.

**Comment by arie1302** [comment]
IMPORTANT : 

Un nouveau fichier MOF impacte
1-extern.mof
2-Ajouter extern.MOF dans MotionRequest.h
3.Création "NomDuMouvement".h
4-Création "NomDuMouvement"Request.h
5-Ajouter extern.MOF dans SpecialActionRequest.h

**Comment by gortium** [comment]
@arie1302 @Bertholome  Done non?

**Comment by Bertholome** [comment]
@gortium :  je vais le tester avant de vous confirmer, normalement demain!
