### ISSUE TITLE
Functionnal GroundPunch

### ISSUE THREAD

**Issue by gortium** [Naova/NaovaCodeRelease#47]
- Good triggers
- Recover behavior (no fall after the action)

**Comment by Bertholome** [comment]
La séquence de mouvement de SidePunch (coté droit) sera revisée cette semaine.

**Comment by AlexD0118** [comment]
Il tombe sur le dos et quand il se relève il ne sait plus il est où

**Comment by bbrulard** [comment]
Traité avec Feature 48 : Sumo
