### ISSUE TITLE
Clean up Git et Waffle 

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#50]
Faire un ménage et valider les documentations des tâches finis

**Comment by gortium** [comment]
### À date se que je ferais avec les branches. 
Je vais édit pour les ???.

LibTactic ---> Merge to devel after sim tests (PR!)            
DevDay ---> ???
Goaler2016 ---> ??? 
Goaler ---> ???
devel ---> Merge to master after IRL tests (PR!)
Conference ---> Delete 
SumoDive ---> ???  
clubConfig ---> Delete  
HeadMovement ---> Merge to devel after sim tests (PR!) 


### Aussi j'aimerais proposer un lien entre waffle et l'état des branches.
ToDo ---> no branch
In Progress ---> New branch + PR to devel + Tests en sim
To Test ---> PR to master + Tests IRL
Done ---> Merged to Master + delete feature branch

**Comment by gortium** [comment]
WIP. Je suis en train de merger LibTactic dans DevDay pour préparer le merge des deux à devel. Je pensais merger LibTactic au devel en premier, puis DevDay ensuite.
