### ISSUE TITLE
******document budget urgent !*********

### ISSUE THREAD

**Issue by jonathanf14** [Naova/NaovaCodeRelease#66]
budget pour les couts de Naova. Preparer tous beau avec les details, un lien du site web de votre qualification, site de RoboCup SPL avec notre nom et voir l'économie fait par le deal pour les nao ;)

Alors:

1) Couts pour 5 Nao (L'equipe a pas de coach maintenant)
2) Frais d'inscription
3) Prix pour les jersey.

**Comment by jonathanf14** [comment]
Englais et francais ! Il faut que cela soit fini au plus criss car en gros on en a besoin pour commander les nao et il faut tout avoir avant le 1 avril sinon on est disqualifier. Ca comprend le faire, le montrer, discuter, achat, livrer ... c'est short en criss faut pas niaiser !

**Comment by L1ghtg1rl** [comment]
Le doc a été crée sur le drive pour débuter la rédaction.
Document administratif --> Sponsorship --> Naova_Rapport financier

**Comment by jonathanf14** [comment]
J'ai mis les chiffres réel, il faudrait juste je pense mettre ca beau.

**Comment by L1ghtg1rl** [comment]
Je peux m'en occuper durant le DevDay/Chalet sans problème

Il nous restera la version EN à faire

**Comment by AlexD0118** [comment]
Le document en français est terminé selon les critères que j'ai compris, il resterait juste la vérification de la version française et en faire la traduction en anglais.

**Comment by L1ghtg1rl** [comment]
J'ai retravaillé les tableaux pour qu'ils soient du meme template que le Doc de commandite
Mais me semble qu'il manque de stock
