### ISSUE TITLE
Mettre le site web sur le GIT

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#74]
Ceci va permettre la modification du site par tous les membres (qui ont les compétence Web) à modifier le contenu du site

**Comment by wmarc04** [comment]
@arie1302 peut tu créer le repo pour le site web, car il faut les droits du github pour créer un nouveau repo. Ensuite @bbrulard va pouvoir mettre le code du site sur le github.

**Comment by arie1302** [comment]
Le repo est créé :)

**Comment by arie1302** [comment]
J'ai réglé vos accès donc tout est good pour le repo du site

**Comment by wmarc04** [comment]
@arie1302 Si tu veux peux commencer a me dresser une liste des modifications que nous souhaitons faire. Je sais qu'on doit mettre les partenaire a jour, mais j'ai pas la vrai liste. Il faut changer les membres avec leurs photos. De plus, il faut mettre a jour la progression des tâches. Autre chose?

**Comment by arie1302** [comment]
1- Ajouter ubisoft comme commanditaire 
      *Doit être sur la page d'accueil et la page de commanditaire
2-Mettre l'équipe à jours :
     *Il faut retirer : 
      a)David Nguyen
      b)Nathalie
      c)Cassandra
      D)David boulay à valider 
     *Modification du nom :
       a)Ariane B. Bétournay
3-Rajouter que nous allons participer à la RoboCup 2018
     *Il faut changer le lien vers la roboCup 2018 mtl. Mettre le site web et nonle lien Facebook.

**Comment by wmarc04** [comment]
C'est fait! Le site est sur git! (fr/en + blog)
