### ISSUE TITLE
Transmission de message entre les robots

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#78]
Changement du nombre de messages par seconde 

Passe de 5 messages à 3 messages.

**Comment by bbrulard** [comment]
Trouvé et modifié dans le fichier "TeammateDataProvider.h"

**Comment by bbrulard** [comment]
/NaovaCodeRelease/Src/Representations/Communication/TeammateData.h$

Infos transmises par les messages  : 


Numero teammate

isGoalkeeper

isPenalized

isUpright

timeWhenLastPacketReceived (timeout 4sec modifiable)

timeOfLastGroundContact

hasGroundContact

status (Penalisé / Tombé / Joue)

RobotPose (Position sur les coordonnes absolues du terrain)

BallModel (coordonnes relatives a la position du coequipier)

ObstacleModel (Coordonnes obstacles relatives a la position du coequipier)

SideConfidence (Confiance dans le fait que le robot joue dans le bon sens)

BehaviorStatus (info behavior)

SPLStandardBehaviorStatus (idem mais formatté facons SPLStandardMessage)

Whistle (output du WhistleRecognizer)

TeammateRoles (role que le teammate devrait utiliser (receveur?Emetteur?))

FieldCoverageLine (derniere ligne du Field Coverage (?))
