### ISSUE TITLE
Avoir un game controller fonctionnel

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#79]
-Comprendre le game controller
-Comprendre comment changer les states 
-Comprendre les fonctions primaires 
-Faire une formation aux membres de l'équipe sur le game controller

**Comment by jonathanf14** [comment]
Je telecharge la nouvelle version 2018 et je vais lancer les games à partir du gameController pour ma serie de test ! après je vais documenter la méthode pour comprende le GameController
