### ISSUE TITLE
Validation du Free Kick Rule + Programmer le Free kick --> tire de pénalité !!!

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#81]
-Quand nous avons une pénalité 
-Quand on se fait pousser et on doit faire un tire de pénalité 
-Shoot out de fin de partie si nous sommes égalité !!

**Comment by bbrulard** [comment]
3.8    Free Kick
A Free Kick is initiated in two circumstances:

In place of an end-line throw-in initiated by the offensive team,  also termed a
Goal Free
Kick
.

A pushing penalty (see Section 4.11) awarded near the ball, termed a
Pushing Free Kick
.
If a team is awarded a Free Kick, the following procedure will apply:
1.  The  head  referee  will  announce  a  Free  Kick,  calling  ”Foul
<
color
><
number
>
”  for  the
pushing robot or ”Goal Free Kick
<
team
>
” for the defensive team.
2.  Game Controller will activate the substate for the Pushing Free Kick or Goal Free Kick,
respectively.  Note that in the case of the Pushing Free Kick the substate is activated auto-
matically through the ”Foul”.
3.  For a Goal Free Kick, the ball will be positioned by the assistant referee, on the Goal Kick
Spot (see figure 10).
16
4.  For a Pushing Free Kick, the ball will be left in place, and only repositioned in accordance
with the pushing rules (see Section 4.11).
5.  The team who is awarded the Free Kick has 30 seconds to complete the Free Kick.
6.  During the Free Kick:
(a)  Only the team awarded with the Free Kick may approach within 0.75m to the ball. The
robots of the other team have to move away from the ball (see Section 4.15).
(b)  Only the opposition Goal Keeper may remain within the 0.75m radius, provided that
the Goal Keeper is within the Goal Box, and does not touch the ball.
(c)  Opposition  robots  that  violate  (a)  or  (b)  are  penalized  with  the  ”Illegal  Defender”
penalty (see Section 4.15 for details) which results in a standard removal penalty (see
Section 4.5).
(d)  Additional penalties against any further robots, including Pushing, do not result in an
additional Free Kick, but still use the appropriate removal penalty.
(e)  The game clock continues to count-down.
7.  A Free Kick is deemed completed and play returns to normal if any of the following occurs:

The team who has been awarded the Free Kick touches the ball.  A robot getting up is
exempt from this rule.

The 30 seconds time period expires.

The game time expires.
8.  The head referee will announce a Free Kick is completed, by ”Free Kick complete”, and the
GameController resumes the game state
playing
. Note that the substate will be automatically
left after the 30 seconds time period expires
