### ISSUE TITLE
Validation de l'impact du retrait "goal keeper rule"

### ISSUE THREAD

**Issue by arie1302** [Naova/NaovaCodeRelease#82]
Il faut voir si le retrait de cette règle nous impact. 

Voici la règle qui est retirer :

3.4 Goal Keeper Save
While within its penalty area, a goal keeper may touch the ball with its arms and/or hands. If a goal keeper is able to lift the ball off of the ground using its arms and/or hands (i. e. using at least one arm or hand), and hold it there for at least 1 second, the ball will be moved to one of the two intersections of a throw-in line and the halfway line. Specifically, the ball will be moved to the intersection point closer (regarding the angle) to the goal keeper at the moment of lifting. If the goal keeper is almost aligned with the field’s x-axis, the referee should use the intersection point at which a teammate is closer at the moment of lifting.
The robot is not required to lift the ball to a particular height in order for the ball to be considered to be ‘lifted off of the ground’, but lack of contact between the ball and ground must be clearly recognizable by the head referee.

**Comment by bbrulard** [comment]
La nouvelle regle dicte "2.2    Goal Keeper
The goal keeper is allowed to touch the ball with its arms/hands only while it is within its own
penalty area. It always has the jersey number “1”." 

Notre Keeper ne souleve pas la balle, et a toujours droit de la toucher avec ses mains. Ce changement ne nous affecte pas.
